name: Check PR for specific file changes

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch all branches
        run: git fetch --all
      - name: Check for file changes
        run: |
          if ! git diff --name-only origin/main | grep -q "TitleBarText.cs"; then
          # 現在のブランチとリモートの main ブランチとの差分を確認。ファイル名 "TitleBarText.cs" が含まれるか調べる。

          echo "TitleBarText.cs has not been changed. Rejecting PR."
          exit 1  # 指定したファイル名が含まれない場合、エラーのコード (1) を返す
          else
          echo "TitleBarText.cs has been changed. Proceeding with PR."
          fi
